import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { format } from 'date-fns';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    headerBox: {
        borderBottomWidth: 2,
        borderBottomColor: '#0B2E59', // Deep Navy
        paddingBottom: 10,
        marginBottom: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: 'extrabold',
        color: '#0B2E59',
        marginBottom: 5,
    },
    metadata: {
        fontSize: 10,
        color: '#555555',
        marginBottom: 3,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#0B2E59',
        borderBottomWidth: 1,
        borderBottomColor: '#DDDDDD',
        paddingBottom: 4,
        marginTop: 20,
        marginBottom: 10,
    },
    summaryContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 10,
    },
    summaryCard: {
        width: '30%',
        marginRight: '3%',
        marginBottom: 10,
        padding: 10,
        backgroundColor: '#F8F9FA',
        borderLeftWidth: 3,
        borderLeftColor: '#0B2E59',
    },
    summaryLabel: {
        fontSize: 9,
        color: '#666666',
        textTransform: 'uppercase',
    },
    summaryValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#111111',
        marginTop: 4,
    },
    table: {
        display: 'flex',
        flexDirection: 'column',
        marginTop: 10,
    },
    tableHeaderRow: {
        flexDirection: 'row',
        backgroundColor: '#0B2E59',
        borderBottomWidth: 1,
        borderBottomColor: '#0B2E59',
        paddingVertical: 8,
        paddingHorizontal: 4,
    },
    tableHeaderCell: {
        color: '#FFFFFF',
        fontSize: 9,
        fontWeight: 'bold',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#EEEEEE',
        paddingVertical: 6,
        paddingHorizontal: 4,
    },
    tableRowZebra: {
        backgroundColor: '#F9F9F9',
    },
    tableCell: {
        fontSize: 8,
        color: '#333333',
    },
    colDate: { width: '10%' },
    colID: { width: '13%' },
    colTruck: { width: '10%' },
    colRoute: { width: '17%' },
    colDist: { width: '8%', textAlign: 'right' },
    colEst: { width: '15%', textAlign: 'right' },
    colAct: { width: '15%', textAlign: 'right' },
    colFinal: { width: '12%', textAlign: 'right' },
    detailText: { fontSize: 6, color: '#666666', marginTop: 2 },
    boldText: { fontWeight: 'bold', marginBottom: 2 },
    footer: {
        position: 'absolute',
        bottom: 20,
        left: 30,
        right: 30,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#DDDDDD',
        paddingTop: 8,
    },
    footerText: {
        fontSize: 8,
        color: '#888888',
        fontStyle: 'italic',
    },
});

export const ReportDocument = ({ data, startDate, endDate, generatedBy }: any) => {
    const { tenantName, executiveSummary, transactionTable, expenseBreakdown } = data;

    const formatCurrency = (val: number) => {
        return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(val);
    };

    const isDateFilterActive = startDate && endDate;

    return (
        <Document title={`Report_${tenantName}_${format(new Date(), 'yyyyMMdd')}`}>
            <Page size="A4" orientation="landscape" style={styles.page}>
                {/* HEADER */}
                <View style={styles.headerBox} fixed>
                    <Text style={styles.title}>{tenantName.toUpperCase()}</Text>
                    <Text style={styles.metadata}>Report Generation Date: {format(new Date(), 'dd MMM yyyy HH:mm')}</Text>
                    <Text style={styles.metadata}>
                        Period: {isDateFilterActive ? `${format(new Date(startDate), 'dd MMM yyyy')} - ${format(new Date(endDate), 'dd MMM yyyy')}` : "All Time"}
                    </Text>
                    <Text style={styles.metadata}>Generated By: {generatedBy}</Text>
                </View>

                {/* EXECUTIVE SUMMARY */}
                <Text style={styles.sectionTitle}>EXECUTIVE SUMMARY</Text>
                <View style={styles.summaryContainer}>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Total Manifests</Text>
                        <Text style={styles.summaryValue}>{executiveSummary.totalManifests} Trips</Text>
                    </View>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Total Distance</Text>
                        <Text style={styles.summaryValue}>{Number(executiveSummary.totalDistance).toLocaleString()} KM</Text>
                    </View>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Grand Total Cost</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(executiveSummary.grandTotalCost)}</Text>
                    </View>
                </View>

                {/* EXPENSE BREAKDOWN (Summary) */}
                <View style={styles.summaryContainer}>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Fuel Costs</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(executiveSummary.totalFuel)}</Text>
                    </View>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Tolls Costs</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(executiveSummary.totalTolls)}</Text>
                    </View>
                    <View style={styles.summaryCard}>
                        <Text style={styles.summaryLabel}>Others Tracker</Text>
                        <Text style={styles.summaryValue}>{formatCurrency(expenseBreakdown['Others'] || 0)}</Text>
                    </View>
                </View>

                {/* DETAILED TRANSACTION TABLE */}
                <Text style={styles.sectionTitle}>DETAILED TRANSACTION LOG</Text>
                <View style={styles.table}>
                    {/* Header */}
                    <View style={styles.tableHeaderRow} fixed>
                        <Text style={[styles.tableHeaderCell, styles.colDate]}>Date</Text>
                        <Text style={[styles.tableHeaderCell, styles.colID]}>Manifest ID</Text>
                        <Text style={[styles.tableHeaderCell, styles.colTruck]}>Truck</Text>
                        <Text style={[styles.tableHeaderCell, styles.colRoute]}>Route</Text>
                        <Text style={[styles.tableHeaderCell, styles.colDist]}>Dist. (KM)</Text>
                        <Text style={[styles.tableHeaderCell, styles.colEst]}>Estimated (Rp)</Text>
                        <Text style={[styles.tableHeaderCell, styles.colAct]}>Actual Added (Rp)</Text>
                        <Text style={[styles.tableHeaderCell, styles.colFinal]}>Final Cost (Rp)</Text>
                    </View>

                    {/* Rows */}
                    {transactionTable.map((row: any, i: number) => {
                        const rowStyle = i % 2 === 0 ? [styles.tableRow, styles.tableRowZebra] : styles.tableRow;
                        return (
                            <View style={rowStyle as any} key={i}>
                                <Text style={[styles.tableCell, styles.colDate]}>{format(new Date(row.date), 'dd/MM/yyyy')}</Text>
                                <Text style={[styles.tableCell, styles.colID]}>{row.manifestId}</Text>
                                <Text style={[styles.tableCell, styles.colTruck]}>{row.truckPlate}</Text>
                                <Text style={[styles.tableCell, styles.colRoute]}>{row.routeStr.length > 25 ? row.routeStr.substring(0, 25) + "..." : row.routeStr}</Text>
                                <Text style={[styles.tableCell, styles.colDist]}>{row.totalDistance.toLocaleString()}</Text>
                                <View style={[styles.tableCell, styles.colEst]}>
                                    <Text style={styles.boldText}>{formatCurrency(row.estimatedCost).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>BBM: {formatCurrency(row.estFuel).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>Tol: {formatCurrency(row.estToll).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>Saku: {formatCurrency(row.estAllowance).replace("Rp", "")}</Text>
                                </View>
                                <View style={[styles.tableCell, styles.colAct]}>
                                    <Text style={styles.boldText}>{formatCurrency(row.actualAddedExpense).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>BBM: {formatCurrency(row.actFuel).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>Bengkel: {formatCurrency(row.actMaintenance).replace("Rp", "")}</Text>
                                    <Text style={styles.detailText}>Lain: {formatCurrency(row.actOthers).replace("Rp", "")}</Text>
                                </View>
                                <Text style={[styles.tableCell, styles.colFinal, styles.boldText]}>{formatCurrency(row.finalCost).replace("Rp", "")}</Text>
                            </View>
                        );
                    })}
                </View>

                {/* FOOTER */}
                <View style={styles.footer} fixed>
                    <Text style={styles.footerText}>Confidential - truxOS</Text>
                    <Text style={styles.footerText} render={({ pageNumber, totalPages }) => (
                        `Page ${pageNumber} of ${totalPages}`
                    )} />
                </View>
            </Page>
        </Document>
    );
};
