import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { calculateEstimatedCost } from "@/lib/estimation";
import ExcelJS from "exceljs";
import { format } from "date-fns";

export async function GET(request: NextRequest) {
    const searchParams = request.nextUrl.searchParams;
    const tenantId = searchParams.get("tenantId");
    const startDateParam = searchParams.get("startDate");
    const endDateParam = searchParams.get("endDate");
    const truckType = searchParams.get("truckType");
    const driverId = searchParams.get("driverId");
    const generatedBy = searchParams.get("generatedBy") || "System User";

    if (!tenantId) {
        return NextResponse.json({ error: "Missing tenantId" }, { status: 400 });
    }

    const whereClause: any = {
        tenantId,
        status: "COMPLETED",
    };

    if (startDateParam && endDateParam) {
        const endDateWithTime = new Date(endDateParam);
        endDateWithTime.setHours(23, 59, 59, 999);

        whereClause.departureDate = {
            gte: new Date(startDateParam),
            lte: endDateWithTime,
        };
    }

    if (truckType) {
        whereClause.truck = {
            type: truckType,
        };
    }
    if (driverId) {
        whereClause.driverId = driverId;
    }

    const manifests = await prisma.manifest.findMany({
        where: whereClause,
        orderBy: { departureDate: "asc" },
        include: {
            truck: true,
            driver: true,
            route: { include: { tolls: true } },
            expenses: true,
            tenant: true,
        },
    });

    if (manifests.length === 0) {
        return NextResponse.json({ error: "No completed manifests found for the selected filters." }, { status: 404 });
    }

    const tenantName = manifests[0].tenant.name;

    // --- PRE-CALCULATE EXECUTIVE SUMMARY ---
    let totalManifests = manifests.length;
    let grandDistance = 0;
    let grandFuel = 0;
    let grandTolls = 0;
    let grandOthers = 0;
    let allFinalCost = 0;

    const exportRows: any[] = [];

    for (const m of manifests) {
        const est = calculateEstimatedCost({
            route: m.route as any,
            truck: m.truck,
            driver: m.driver,
            additionalDistanceKm: m.additionalDistanceKm,
        });

        const manifestDistance = m.route.baseDistanceKm + m.additionalDistanceKm;
        grandDistance += manifestDistance;

        let actFuel = 0;
        let actMaintenance = 0;
        let actOthers = 0;
        let actTotal = 0;

        for (const exp of m.expenses) {
            const val = Number(exp.amount || 0);
            actTotal += val;
            if (exp.category === "BAHAN_BAKAR") actFuel += val;
            else if (exp.category === "PERBAIKAN") actMaintenance += val;
            else actOthers += val;
        }

        const estTotal = Number(m.totalEstimatedCost || 0);
        const finalCost = estTotal + actTotal;

        grandFuel += (actFuel || est.fuelCost);
        grandTolls += (actOthers || est.tollCost); // Roughly grouping tolls/others
        grandOthers += actOthers;
        allFinalCost += finalCost;

        exportRows.push({
            m,
            manifestDistance,
            estTotal,
            estFuel: est.fuelCost,
            estToll: est.tollCost,
            estAllowance: est.allowance,
            actTotal,
            actFuel,
            actMaintenance,
            actOthers,
            finalCost,
        });
    }

    // --- BUILD WORKBOOK ---
    const workbook = new ExcelJS.Workbook();
    workbook.creator = tenantName;
    workbook.lastModifiedBy = generatedBy;
    workbook.created = new Date();
    workbook.modified = new Date();

    const sheet = workbook.addWorksheet("Transaction Report", {
        views: [{ showGridLines: false }] // Clean dashboard look
    });

    // Color tokens
    const NAVY = "FF0B2E59";
    const GREY_BG = "FFF8F9FA";
    const BORDER = "FFDDDDDD";

    // FORMATTER
    const formatRp = (val: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(val);

    // 1. KOP SURAT
    sheet.getCell("A1").value = tenantName.toUpperCase();
    sheet.getCell("A1").font = { size: 18, bold: true, color: { argb: NAVY } };
    sheet.getCell("A2").value = `Report Generation Date: ${format(new Date(), "dd MMM yyyy HH:mm")}`;
    sheet.getCell("A3").value = `Period: ${startDateParam ? format(new Date(startDateParam), "dd MMM yyyy") : "All Time"} - ${endDateParam ? format(new Date(endDateParam), "dd MMM yyyy") : "All Time"}`;
    sheet.getCell("A4").value = `Generated By: ${generatedBy}`;
    for (let i = 2; i <= 4; i++) sheet.getCell(`A${i}`).font = { size: 10, color: { argb: "FF555555" } };

    // Divider Line
    sheet.getCell("A5").border = { bottom: { style: "medium", color: { argb: NAVY } } };
    sheet.mergeCells("A5:H5");

    // 2. EXECUTIVE SUMMARY
    sheet.getCell("A7").value = "1. EXECUTIVE SUMMARY";
    sheet.getCell("A7").font = { size: 12, bold: true, color: { argb: NAVY } };

    // Row 9 & 10: Top Row Data
    sheet.getRow(9).values = ["Total Trips", "", "", "Total Distance", "", "", "Grand Total Cost", ""];
    sheet.getRow(9).font = { size: 9, bold: true, color: { argb: "FF666666" } };
    sheet.getRow(10).values = [
        `${totalManifests} Trips`, "", "",
        `${grandDistance.toLocaleString()} KM`, "", "",
        formatRp(allFinalCost), ""
    ];
    sheet.getRow(10).font = { size: 14, bold: true, color: { argb: "FF111111" } };

    // Row 12 & 13: Bottom Row Data (with 1 row space)
    sheet.getRow(12).values = ["Fuel Spending (Est. + Act)", "", "", "Toll Spending (Est. + Others)", "", "", "Total Allowance (Est. Saku)", ""];
    sheet.getRow(12).font = { size: 9, bold: true, color: { argb: "FF666666" } };

    // Add Allowance variable calc
    let grandAllowance = 0;
    exportRows.forEach(r => grandAllowance += r.estAllowance);

    sheet.getRow(13).values = [
        formatRp(grandFuel), "", "",
        formatRp(grandTolls), "", "",
        formatRp(grandAllowance), ""
    ];
    sheet.getRow(13).font = { size: 14, bold: true, color: { argb: "FF111111" } };

    // Merge styling blocks for Grid with spacing
    const blocks = [
        { row: 9, col: 1 }, { row: 9, col: 4 }, { row: 9, col: 7 },
        { row: 12, col: 1 }, { row: 12, col: 4 }, { row: 12, col: 7 }
    ];

    blocks.forEach(b => {
        sheet.mergeCells(b.row, b.col, b.row, b.col + 1);
        sheet.mergeCells(b.row + 1, b.col, b.row + 1, b.col + 1);

        const lblCell = sheet.getCell(b.row, b.col);
        const valCell = sheet.getCell(b.row + 1, b.col);

        lblCell.border = { left: { style: "thick", color: { argb: NAVY } }, top: { style: "thin", color: { argb: BORDER } }, right: { style: "thin", color: { argb: BORDER } } };
        valCell.border = { left: { style: "thick", color: { argb: NAVY } }, bottom: { style: "thin", color: { argb: BORDER } }, right: { style: "thin", color: { argb: BORDER } } };

        lblCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: GREY_BG } };
        valCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: GREY_BG } };
    });

    // 3. DETAILED TABLE
    sheet.getCell("A16").value = "2. DETAILED TRANSACTION LOG";
    sheet.getCell("A16").font = { size: 12, bold: true, color: { argb: NAVY } };

    const headerRowNum = 18;
    sheet.getRow(headerRowNum).values = [
        "Date", "Manifest ID", "Truck / Driver", "Route", "Dist. (KM)",
        "Estimated Breakdown (Rp)", "Actual Added Breakdown (Rp)", "Final Cost (Rp)"
    ];

    const headerRow = sheet.getRow(headerRowNum);
    headerRow.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 11 };
    headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
    headerRow.alignment = { vertical: "middle", horizontal: "center" };

    // Add Data
    for (const data of exportRows) {
        // Multi-line rich text mimicking the stacked UI detail layout
        const estText = {
            richText: [
                { text: `${formatRp(data.estTotal)}\n`, font: { bold: true, size: 11 } },
                { text: `  • BBM: ${formatRp(data.estFuel)}\n`, font: { size: 9, color: { argb: "FF555555" } } },
                { text: `  • Tol: ${formatRp(data.estToll)}\n`, font: { size: 9, color: { argb: "FF555555" } } },
                { text: `  • Saku: ${formatRp(data.estAllowance)}`, font: { size: 9, color: { argb: "FF555555" } } }
            ]
        };

        const actText = {
            richText: [
                { text: `${formatRp(data.actTotal)}\n`, font: { bold: true, size: 11 } },
                { text: `  • BBM: ${formatRp(data.actFuel)}\n`, font: { size: 9, color: { argb: "FF555555" } } },
                { text: `  • Bengkel: ${formatRp(data.actMaintenance)}\n`, font: { size: 9, color: { argb: "FF555555" } } },
                { text: `  • Lain: ${formatRp(data.actOthers)}`, font: { size: 9, color: { argb: "FF555555" } } }
            ]
        };

        const row = sheet.addRow([
            new Date(data.m.departureDate),
            data.m.manifestNumber,
            `${data.m.truck.licensePlate}\n(${data.m.driver.fullName})`,
            `${data.m.route.origin} - ${data.m.route.destination}`,
            data.manifestDistance,
            "EST_PHOLDER",
            "ACT_PHOLDER",
            data.finalCost
        ]);

        // Replace rich text objects safely
        sheet.getCell(`F${row.number}`).value = estText;
        sheet.getCell(`G${row.number}`).value = actText;

        row.height = 75; // Provide visual height for the multiline items
        row.alignment = { vertical: "top" };

        // Formatting cells
        sheet.getCell(`A${row.number}`).alignment = { vertical: "top", horizontal: "left" };
        sheet.getCell(`C${row.number}`).alignment = { vertical: "top", horizontal: "left", wrapText: true };
        sheet.getCell(`D${row.number}`).alignment = { vertical: "top", horizontal: "left", wrapText: true };
        sheet.getCell(`E${row.number}`).alignment = { vertical: "top", horizontal: "center" };
        sheet.getCell(`F${row.number}`).alignment = { vertical: "top", horizontal: "left", wrapText: true };
        sheet.getCell(`G${row.number}`).alignment = { vertical: "top", horizontal: "left", wrapText: true };
        sheet.getCell(`H${row.number}`).alignment = { vertical: "top", horizontal: "right" };

        // Add subtle zebra border separating rows
        row.eachCell({ includeEmpty: false }, (cell) => {
            cell.border = { bottom: { style: "thin", color: { argb: BORDER } } };
        });
    }

    // Filter functionality
    sheet.autoFilter = `A${headerRowNum}:H${headerRowNum}`;

    // Fix column widths
    const currencyFormat = '_("Rp"* #,##0_);_("Rp"* (#,##0);_("Rp"* "-"_);_(@_)';
    sheet.getColumn(1).numFmt = "dd-mmm-yyyy";
    sheet.getColumn(1).width = 15;
    sheet.getColumn(2).width = 20;
    sheet.getColumn(3).width = 25; // Truck/Driver combo
    sheet.getColumn(4).width = 32; // Route
    sheet.getColumn(5).width = 12; // Dist
    sheet.getColumn(5).numFmt = "#,##0.0";
    sheet.getColumn(6).width = 30; // Est Breakdown (Rich Text)
    sheet.getColumn(7).width = 30; // Act Breakdown (Rich Text)

    // Total is numeric
    sheet.getColumn(8).width = 18;
    sheet.getColumn(8).numFmt = currencyFormat;

    const buffer = await workbook.xlsx.writeBuffer();
    const response = new NextResponse(buffer);
    response.headers.set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    response.headers.set("Content-Disposition", `attachment; filename=Report_${tenantName.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd_HHmm')}.xlsx`);

    return response;
}
